version: "2"

linters:
  default: none
  enable:
    - misspell
    - ineffassign

issues:
  exclude-rules:
    - path: vendor
      linters:
        - all

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly