// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: dns.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_RECORD_RESERVED RecordType = 0
	RecordType_TYPE_A          RecordType = 1
	RecordType_TYPE_NS         RecordType = 2
	RecordType_TYPE_CNAME      RecordType = 5
	RecordType_TYPE_PTR        RecordType = 12
	RecordType_TYPE_MX         RecordType = 15
	RecordType_TYPE_TXT        RecordType = 16
	RecordType_TYPE_AAAA       RecordType = 28
	RecordType_TYPE_SRV        RecordType = 33
	RecordType_TYPE_HTTPS      RecordType = 65
	RecordType_TYPE_SVCB       RecordType = 64
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0:  "RECORD_RESERVED",
		1:  "TYPE_A",
		2:  "TYPE_NS",
		5:  "TYPE_CNAME",
		12: "TYPE_PTR",
		15: "TYPE_MX",
		16: "TYPE_TXT",
		28: "TYPE_AAAA",
		33: "TYPE_SRV",
		65: "TYPE_HTTPS",
		64: "TYPE_SVCB",
	}
	RecordType_value = map[string]int32{
		"RECORD_RESERVED": 0,
		"TYPE_A":          1,
		"TYPE_NS":         2,
		"TYPE_CNAME":      5,
		"TYPE_PTR":        12,
		"TYPE_MX":         15,
		"TYPE_TXT":        16,
		"TYPE_AAAA":       28,
		"TYPE_SRV":        33,
		"TYPE_HTTPS":      65,
		"TYPE_SVCB":       64,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_dns_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_dns_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{0}
}

type DNSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          RecordType             `protobuf:"varint,2,opt,name=type,proto3,enum=dns.RecordType" json:"type,omitempty"`
	Class_        uint32                 `protobuf:"varint,3,opt,name=class_,json=class,proto3" json:"class_,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	RdLength      uint32                 `protobuf:"varint,5,opt,name=rd_length,json=rdLength,proto3" json:"rd_length,omitempty"`
	Rdata         []byte                 `protobuf:"bytes,6,opt,name=rdata,proto3" json:"rdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{0}
}

func (x *DNSRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSRecord) GetType() RecordType {
	if x != nil {
		return x.Type
	}
	return RecordType_RECORD_RESERVED
}

func (x *DNSRecord) GetClass_() uint32 {
	if x != nil {
		return x.Class_
	}
	return 0
}

func (x *DNSRecord) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DNSRecord) GetRdLength() uint32 {
	if x != nil {
		return x.RdLength
	}
	return 0
}

func (x *DNSRecord) GetRdata() []byte {
	if x != nil {
		return x.Rdata
	}
	return nil
}

var File_dns_proto protoreflect.FileDescriptor

const file_dns_proto_rawDesc = "" +
	"\n" +
	"\tdns.proto\x12\x03dns\"\xa0\x01\n" +
	"\tDNSRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.dns.RecordTypeR\x04type\x12\x15\n" +
	"\x06class_\x18\x03 \x01(\rR\x05class\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x1b\n" +
	"\trd_length\x18\x05 \x01(\rR\brdLength\x12\x14\n" +
	"\x05rdata\x18\x06 \x01(\fR\x05rdata*\xaf\x01\n" +
	"\n" +
	"RecordType\x12\x13\n" +
	"\x0fRECORD_RESERVED\x10\x00\x12\n" +
	"\n" +
	"\x06TYPE_A\x10\x01\x12\v\n" +
	"\aTYPE_NS\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_CNAME\x10\x05\x12\f\n" +
	"\bTYPE_PTR\x10\f\x12\v\n" +
	"\aTYPE_MX\x10\x0f\x12\f\n" +
	"\bTYPE_TXT\x10\x10\x12\r\n" +
	"\tTYPE_AAAA\x10\x1c\x12\f\n" +
	"\bTYPE_SRV\x10!\x12\x0e\n" +
	"\n" +
	"TYPE_HTTPS\x10A\x12\r\n" +
	"\tTYPE_SVCB\x10@B5Z3github.com/ram1234598766-dotcom/Local-WEB/pkg/protob\x06proto3"

var (
	file_dns_proto_rawDescOnce sync.Once
	file_dns_proto_rawDescData []byte
)

func file_dns_proto_rawDescGZIP() []byte {
	file_dns_proto_rawDescOnce.Do(func() {
		file_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)))
	})
	return file_dns_proto_rawDescData
}

var file_dns_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dns_proto_goTypes = []any{
	(RecordType)(0),   // 0: dns.RecordType
	(*DNSRecord)(nil), // 1: dns.DNSRecord
}
var file_dns_proto_depIdxs = []int32{
	0, // 0: dns.DNSRecord.type:type_name -> dns.RecordType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dns_proto_init() }
func file_dns_proto_init() {
	if File_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dns_proto_goTypes,
		DependencyIndexes: file_dns_proto_depIdxs,
		EnumInfos:         file_dns_proto_enumTypes,
		MessageInfos:      file_dns_proto_msgTypes,
	}.Build()
	File_dns_proto = out.File
	file_dns_proto_goTypes = nil
	file_dns_proto_depIdxs = nil
}
