// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_PING          MessageType = 0
	MessageType_MSG_PONG          MessageType = 1
	MessageType_MSG_FIND_NODE     MessageType = 2
	MessageType_MSG_FOUND_NODE    MessageType = 3
	MessageType_MSG_STORE         MessageType = 4
	MessageType_MSG_FIND_VALUE    MessageType = 5
	MessageType_MSG_FOUND_VALUE   MessageType = 6
	MessageType_MSG_REGISTER_NODE MessageType = 7
	MessageType_MSG_ANNOUNCE      MessageType = 8
	MessageType_MSG_HEARTBEAT     MessageType = 9
	MessageType_MSG_RELAY         MessageType = 10
	MessageType_MSG_RELAY_ACK     MessageType = 11
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MSG_PING",
		1:  "MSG_PONG",
		2:  "MSG_FIND_NODE",
		3:  "MSG_FOUND_NODE",
		4:  "MSG_STORE",
		5:  "MSG_FIND_VALUE",
		6:  "MSG_FOUND_VALUE",
		7:  "MSG_REGISTER_NODE",
		8:  "MSG_ANNOUNCE",
		9:  "MSG_HEARTBEAT",
		10: "MSG_RELAY",
		11: "MSG_RELAY_ACK",
	}
	MessageType_value = map[string]int32{
		"MSG_PING":          0,
		"MSG_PONG":          1,
		"MSG_FIND_NODE":     2,
		"MSG_FOUND_NODE":    3,
		"MSG_STORE":         4,
		"MSG_FIND_VALUE":    5,
		"MSG_FOUND_VALUE":   6,
		"MSG_REGISTER_NODE": 7,
		"MSG_ANNOUNCE":      8,
		"MSG_HEARTBEAT":     9,
		"MSG_RELAY":         10,
		"MSG_RELAY_ACK":     11,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=message.MessageType" json:"type,omitempty"`
	Src           []byte                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst           []byte                 `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_PING
}

func (x *Message) GetSrc() []byte {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *Message) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"q\n" +
	"\aMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.message.MessageTypeR\x04type\x12\x10\n" +
	"\x03src\x18\x02 \x01(\fR\x03src\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\fR\x03dst\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload*\xe6\x01\n" +
	"\vMessageType\x12\f\n" +
	"\bMSG_PING\x10\x00\x12\f\n" +
	"\bMSG_PONG\x10\x01\x12\x11\n" +
	"\rMSG_FIND_NODE\x10\x02\x12\x12\n" +
	"\x0eMSG_FOUND_NODE\x10\x03\x12\r\n" +
	"\tMSG_STORE\x10\x04\x12\x12\n" +
	"\x0eMSG_FIND_VALUE\x10\x05\x12\x13\n" +
	"\x0fMSG_FOUND_VALUE\x10\x06\x12\x15\n" +
	"\x11MSG_REGISTER_NODE\x10\a\x12\x10\n" +
	"\fMSG_ANNOUNCE\x10\b\x12\x11\n" +
	"\rMSG_HEARTBEAT\x10\t\x12\r\n" +
	"\tMSG_RELAY\x10\n" +
	"\x12\x11\n" +
	"\rMSG_RELAY_ACK\x10\vB5Z3github.com/ram1234598766-dotcom/Local-WEB/pkg/protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(MessageType)(0), // 0: message.MessageType
	(*Message)(nil),  // 1: message.Message
}
var file_message_proto_depIdxs = []int32{
	0, // 0: message.Message.type:type_name -> message.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
